version: "3.9"
services:
  carina:
    environment:
      - SUITE_NAME=${SUITE_NAME}
    build: ./
    volumes:
      - /Users/solvd/Downloads/target:/target
      - /Users/solvd/Downloads/reports:/reports